language: cpp

dist: bionic

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="debug_symbols=no verbose=yes progress=no builtin_libpng=yes no_editor_splash=yes use_static_cpp=yes builtin_freetype=yes builtin_libpng=yes builtin_zlib=yes use_llvm=yes"
    - MODULES_DISABLED=$(cat misc/ci/modules_disabled.txt)
    - GODOT_REPO_URL="https://github.com/godotengine/godot"
    - GODOT_DIR="godot"
cache:
  directories:
    - $SCONS_CACHE

jobs:
  include:
    - name: Linux editor (debug, GCC 9, with Mono)
      stage: build
      env: PLATFORM=linuxbsd TOOLS=yes TARGET=debug CACHE_NAME=${PLATFORM}-tools-mono-gcc-9 MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" EXTRA_ARGS="module_mono_enabled=yes mono_glue=no"
      os: linux
      compiler: gcc-9
      addons:
        apt:
          sources:
            - sourceline: "deb https://download.mono-project.com/repo/ubuntu stable-bionic main"
              key_url: "https://raw.githubusercontent.com/travis-ci/apt-source-safelist/master/keys/mono.asc"
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - &gcc9_deps [gcc-9, g++-9]
            - &linux_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]
            - &linux_mono_deps [mono-devel, msbuild, nuget]

    - name: Linux export template (release, Clang 7)
      stage: build
      env: PLATFORM=linuxbsd TOOLS=no TARGET=release CACHE_NAME=${PLATFORM}-clang
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *linux_deps

    - name: Android export template (release_debug, Clang)
      stage: build
      env: PLATFORM=android TOOLS=no TARGET=release_debug CACHE_NAME=${PLATFORM}-clang
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - openjdk-8-jdk

    - name: macOS editor (debug, Clang)
      stage: build
      env: PLATFORM=osx TOOLS=yes TARGET=debug CACHE_NAME=${PLATFORM}-tools-clang
      os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          packages:
            - scons
          update: true

    - name: Linux export template (release_debug, GCC 7, without 3D support)
      stage: build
      env: PLATFORM=linuxbsd TOOLS=no TARGET=release_debug CACHE_NAME=${PLATFORM}-gcc-7 EXTRA_ARGS="disable_3d=yes"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - *linux_deps

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.8 system;
      pip3 install --user scons;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PLATFORM" = "android" ]; then
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64;
      export PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:${PATH};
      java -version;
      misc/ci/travis/android-tools-linux.sh;
    fi

before_script:
  - if [ "$PLATFORM" = "android" ]; then
      export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
      export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk;
    fi

  - cd
  - git clone --depth=1 "$GODOT_REPO_URL"
  - cd "godot/"
  - ln -s $TRAVIS_BUILD_DIR "modules/imagetools"

script:
  - scons -j2 CC=$CC CXX=$CXX platform=$PLATFORM tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS $MODULES_DISABLED
